/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdlib.h>
#include "platform_Types.h"

#define RCC_base		0x40021000
#define GPIOA_base		0x40010800

#define RCC_APB2ENR			*(vuint32_t*) (RCC_base+ 0X18)

#define	GPIOA_CRH		 	*(vuint32_t*)( GPIOA_base+ 0X04)
#define	GPIOA_ODR			*(vuint32_t*)( GPIOA_base+ 0x0c)
#define	GPIOA_CRL			*(vuint32_t*)( GPIOA_base+ 0x00)
#define	GPIOA_IDR			*(vuint32_t*)( GPIOA_base+ 0x08)

#define GPIOB_base			0x40010C00
#define	GPIOB_CRH		 	*(vuint32_t*)( GPIOB_base+ 0X04)
#define	GPIOB_ODR			*(vuint32_t*)( GPIOB_base+ 0x0c)
#define	GPIOB_CRL			*(vuint32_t*)( GPIOB_base+ 0x00)
#define	GPIOB_IDR			*(vuint32_t*)( GPIOB_IDR+ 0x08)



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



void mywait(int x){
	vuint32_t z,y;
	for(y=0;y<x;y++)
	{
		for(z=0;z<255;z++);

	}
}



int main(void)
{
	// Enable PortA and PortB clocks
	RCC_APB2ENR |= 1<<2;
	RCC_APB2ENR |= 1<<3;

	GPIOA_CRL =0x0;
	GPIOB_CRL =0x0;

	// PA1 input HZ
	GPIOA_CRL |= 1<<6;

	// PA13 input HZ
	GPIOA_CRH &= ~(0b11<<20);
	GPIOA_CRH  |= 0b11<<22;

	// PB1 output push-pull
	GPIOB_CRL |= 0b01<<4;

	// PB13 output push-pull
	GPIOB_CRH  |= 0b01<<20;
	GPIOB_CRH &= ~(0b11<<22);

	while(1){
		if ((GPIOA_IDR & 1<<1)>>1 == 0)
		{
			GPIOB_ODR ^=  1<<1;
			while((GPIOA_IDR & 1<<1)>>1 == 0);
		}

		if ( (GPIOA_IDR & 1<<13) >>13 == 1)
		{
			GPIOB_ODR ^=  1<<13;


		}

		mywait(1);
	}
}
