/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "Stm32_F103C6_GPIO_drivers.h"
#include "keypad.h"
#include "LCD.h"
#include "7seg.h"
#include "Stm32_F103C6_EXTI_drivers.h"



void APP( void ){

	LCD_WRITE_STRING("IQR EXTI is HAPPENED _|-");

}

int main(void)
{
	RCC_GPIOB_CLK_ENABLE();
	RCC_GPIOA_CLK_ENABLE();

	GPIO_PinConfig_t PIN_CONFIG;
	PIN_CONFIG.GPIO_Mode= GPIO_MODE_INPUT_FLO;
	PIN_CONFIG.GPIO_PinNumber= GPIO_PIN_9;
	MCAL_GPIO_Init(GPIOB, &PIN_CONFIG);

	EXTI_PinConfig_t EXTI_config;
	EXTI_config.EXTI_PIN= EXTI9PB9;
	EXTI_config.IRQ_EN = EXTI_IRQ_Enable;
	EXTI_config.Trigger_case= EXTI_Trigger_FALLING;
	EXTI_config.P_IRQCallBack= &APP;
	MCAL_EXTI_GPIO_Init(&EXTI_config);

	LCD_INIT();

	while(1)
	{

	}
}
