/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include "platform_Types.h"


#define RCC_BASE 	0x40021000
#define RCC_CFGR    *(vuint32_t *)(RCC_BASE+0x04)
#define RCC_CR    *(vuint32_t *)(RCC_BASE+0x00)


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{

	// SW=10
	RCC_CFGR |= 0b10<<0;
	//PLLMUL= 0110
	RCC_CFGR |= 0b0110<<18;
	//PPRE1= 100
	RCC_CFGR |= 0b100<<8;

	//PPRE1= 101
	RCC_CFGR |= 0b101<<11;


	RCC_CR |= 1<<24;



	/* Loop forever */
	while(1)
	{

	}
}
