/*
 * CFile1.c
 *
 * Created: 10/28/2023 10:43:00 PM
 *  Author: abdoo
 */ 

#include "7seg.h"

extern void mywait(int x);


void Seven_Seg_OFF(void){
	MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_0, SEVEN_SEG_PIN_OFF);
	MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_1, SEVEN_SEG_PIN_OFF);
	MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_2, SEVEN_SEG_PIN_OFF);
	MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_3, SEVEN_SEG_PIN_OFF);
	MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_4, SEVEN_SEG_PIN_OFF);
	MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_5, SEVEN_SEG_PIN_OFF);
	MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_6, SEVEN_SEG_PIN_OFF);
}


void seven_seg_init(void){
	uint32_t delay=200;

	RCC_GPIOB_CLK_ENABLE();
	GPIO_PinConfig_t pinConfig;
	pinConfig.GPIO_PinNumber=SEVEN_SEG_PIN_0;
	pinConfig.GPIO_Mode= GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_Output_Speed= GPPIO_SPEED_10M;
	MCAL_GPIO_Init(SEVEN_SEG_PORT, &pinConfig);
	pinConfig.GPIO_PinNumber=SEVEN_SEG_PIN_1;
	pinConfig.GPIO_Mode= GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_Output_Speed= GPPIO_SPEED_10M;
	MCAL_GPIO_Init(SEVEN_SEG_PORT, &pinConfig);
	pinConfig.GPIO_PinNumber=SEVEN_SEG_PIN_2;
	pinConfig.GPIO_Mode= GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_Output_Speed= GPPIO_SPEED_10M;
	MCAL_GPIO_Init(SEVEN_SEG_PORT, &pinConfig);
	pinConfig.GPIO_PinNumber=SEVEN_SEG_PIN_3;
	pinConfig.GPIO_Mode= GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_Output_Speed= GPPIO_SPEED_10M;
	MCAL_GPIO_Init(SEVEN_SEG_PORT, &pinConfig);
	pinConfig.GPIO_PinNumber=SEVEN_SEG_PIN_4;
	pinConfig.GPIO_Mode= GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_Output_Speed= GPPIO_SPEED_10M;
	MCAL_GPIO_Init(SEVEN_SEG_PORT, &pinConfig);
	pinConfig.GPIO_PinNumber=SEVEN_SEG_PIN_5;
	pinConfig.GPIO_Mode= GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_Output_Speed= GPPIO_SPEED_10M;
	MCAL_GPIO_Init(SEVEN_SEG_PORT, &pinConfig);
	pinConfig.GPIO_PinNumber=SEVEN_SEG_PIN_6;
	pinConfig.GPIO_Mode= GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_Output_Speed= GPPIO_SPEED_10M;
	MCAL_GPIO_Init(SEVEN_SEG_PORT, &pinConfig);
	Seven_Seg_OFF();
	mywait(delay);
//	seven_seg_write(0);
//	mywait(delay);
//	seven_seg_write(1);
//	mywait(delay);
//	seven_seg_write(2);
//	mywait(delay);
//	seven_seg_write(3);
//	mywait(delay);
//	seven_seg_write(4);
//	mywait(delay);
//	seven_seg_write(5);
//	mywait(delay);
//	seven_seg_write(6);
//	mywait(delay);
//	seven_seg_write(7);
//	mywait(delay);
//	seven_seg_write(8);
//	mywait(delay);
//	seven_seg_write(9);

}











void seven_seg_write(int num){
	Seven_Seg_OFF();
	switch (num){
	case 1:
		PORTD=0b00000110;
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_0, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_1, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_2, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_3, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_4, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_5, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_6, SEVEN_SEG_PIN_OFF);
		break;
	case 2:
		PORTD=0b01011011;
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_0, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_1, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_2, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_3, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_4, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_5, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_6, SEVEN_SEG_PIN_ON);
		break;
	case 3:
		PORTD=0b01001111;	
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_0, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_1, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_2, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_3, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_4, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_5, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_6, SEVEN_SEG_PIN_ON);
		break;
	case 4:
		PORTD=0b01100110;
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_0, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_1, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_2, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_3, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_4, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_5, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_6, SEVEN_SEG_PIN_ON);
		break;
	case 5:
		PORTD=0b01101101;
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_0, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_1, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_2, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_3, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_4, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_5, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_6, SEVEN_SEG_PIN_ON);

		break;
	case 6:
		PORTD=0b01111101;
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_0, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_1, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_2, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_3, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_4, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_5, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_6, SEVEN_SEG_PIN_ON);
		break;
	case 7:
		PORTD=0b00000111;
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_0, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_1, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_2, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_3, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_4, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_5, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_6, SEVEN_SEG_PIN_OFF);
		break;
	case 8:
		PORTD=0b01111111;
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_0, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_1, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_2, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_3, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_4, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_5, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_6, SEVEN_SEG_PIN_ON);

		break;

	case 0:
		PORTD=0b01111111;
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_0, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_1, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_2, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_3, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_4, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_5, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_6, SEVEN_SEG_PIN_OFF);

		break;

	case 9:
		PORTD=0b01111111;
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_0, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_1, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_2, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_3, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_4, SEVEN_SEG_PIN_OFF);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_5, SEVEN_SEG_PIN_ON);
		MCAL_GPIO_WritePin(SEVEN_SEG_PORT, SEVEN_SEG_PIN_6, SEVEN_SEG_PIN_ON);

		break;

	}


}
