/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stm32f103x6.h"
#include "Stm32_F103C6_GPIO_drivers.h"
#include "KEYBAD.h"
#include "LCD.h"
#include "7seg.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



void mywait(int x){
	volatile uint32_t z,y;
	for(y=0;y<x;y++)
	{
		for(z=0;z<255;z++);

	}
}


int main(void)
{

	RCC_GPIOA_CLK_ENABLE();
	RCC_GPIOB_CLK_ENABLE();

	//	seven_seg_init();
	LCD_INIT();



	while(1)
	{
		LCD_WRITE_CHAR( 'A' );

	}

}
