/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "Stm32_F103C6_GPIO_drivers.h"
#include "Stm32f103x6.h"
#include "Stm32_F103C6_USART_drivers.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


uint8_t data;

void USART_IRQ(void)
{
	MCAL_USART_RecieveData(USART1, &data, disable);
	MCAL_USART_SendData(USART1, &data, enable);

}



int main(void)
{
	// Enable PortA and PortB clocks
	RCC_GPIOA_CLK_ENABLE();
	RCC_GPIOB_CLK_ENABLE();
	RCC_AFIO_CLK_ENABLE();
	USART_Config UART_confg;
	UART_confg.Baudrate= USART_BaudRate_115200;
	UART_confg.HwFlowControl= USART_HwFlowControl_None;
	UART_confg.IRQ_Enable= USART_IRQ_Enable_RXNE;
	UART_confg.P_IRQ_CallBack= USART_IRQ;
	UART_confg.Parity= USART_Parity_Disable;
	UART_confg.Payload_length= USART_Payload_length_8bit;
	UART_confg.StopBits= USART_StopBits_1Bit;
	UART_confg.USART_Mode= USART_Mode_Tx_Rx;
	MCAL_USART_Init(USART1, &UART_confg);
	MCAL_USART_GPIO_SetPins(USART1);

	while(1){


	}
}

